spring:
  application:
    name: ConnectSphere
  datasource:
    # ğŸš¨ DÄ°KKAT: Buradaki URL kÄ±smÄ±na o kutudaki linkin baÅŸ kÄ±smÄ±nÄ± yazÄ±yoruz
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.hwnbafmokyuiblojykgy
    # ğŸš¨ Buraya Supabase projesini kurarken belirlediÄŸin ÅŸifreyi yaz
    password: 2461.Ergun36
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # Ãœcretsiz plan olduÄŸu iÃ§in dÃ¼ÅŸÃ¼k tutuyoruz
      keepalive-time: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: connectSphereSuperSecretKeyConnectSphere12345
  expiration: 86400000

cloudinary:
  cloud-name: dic1upwwe
  api-key: 334669717675515
  api-secret: AaFaQXkfpM77wefhuj8BXfQSAls